// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-tbzbmghBohKai6COSB8j-SZTiiKKo7I',
    appId: '1:437845037464:web:29bb4fe176676384625bed',
    messagingSenderId: '437845037464',
    projectId: 'golf-force-plate-app',
    authDomain: 'golf-force-plate-app.firebaseapp.com',
    storageBucket: 'golf-force-plate-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDth_GoljkfITrV3-gCJaiZDjKKCu-3JMc',
    appId: '1:437845037464:android:527ce68525a451fa625bed',
    messagingSenderId: '437845037464',
    projectId: 'golf-force-plate-app',
    storageBucket: 'golf-force-plate-app.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-tbzbmghBohKai6COSB8j-SZTiiKKo7I',
    appId: '1:437845037464:web:f8641a9d0a235e31625bed',
    messagingSenderId: '437845037464',
    projectId: 'golf-force-plate-app',
    authDomain: 'golf-force-plate-app.firebaseapp.com',
    storageBucket: 'golf-force-plate-app.firebasestorage.app',
  );
}
